// <auto-generated />
namespace HelpDesk.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HelpDeskContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HelpDeskContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201408170049244_HelpDeskContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
